<?php
/**
 * EnvironmentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kinde\KindeSDK\Test\Api;

use \Kinde\KindeSDK\Configuration;
use \Kinde\KindeSDK\ApiException;
use \Kinde\KindeSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EnvironmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvironmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteEnvironementFeatureFlagOverride
     *
     * Delete environment feature flag override.
     *
     */
    public function testDeleteEnvironementFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEnvironementFeatureFlagOverrides
     *
     * Delete all environment feature flag overrides.
     *
     */
    public function testDeleteEnvironementFeatureFlagOverrides()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEnvironementFeatureFlagOverride
     *
     * Update environment feature flag override.
     *
     */
    public function testUpdateEnvironementFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
