<?php
/**
 * OrganizationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kinde\KindeSDK\Test\Api;

use \Kinde\KindeSDK\Configuration;
use \Kinde\KindeSDK\ApiException;
use \Kinde\KindeSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addOrganizationUsers
     *
     * Add Organization Users.
     *
     */
    public function testAddOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganization
     *
     * Create Organization.
     *
     */
    public function testCreateOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationUserPermission
     *
     * Add Organization User Permission.
     *
     */
    public function testCreateOrganizationUserPermission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationUserRole
     *
     * Add Organization User Role.
     *
     */
    public function testCreateOrganizationUserRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganization
     *
     * Delete Organization.
     *
     */
    public function testDeleteOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationFeatureFlagOverride
     *
     * Delete Organization Feature Flag Override.
     *
     */
    public function testDeleteOrganizationFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationFeatureFlagOverrides
     *
     * Delete Organization Feature Flag Overrides.
     *
     */
    public function testDeleteOrganizationFeatureFlagOverrides()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationUserPermission
     *
     * Delete Organization User Permission.
     *
     */
    public function testDeleteOrganizationUserPermission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationUserRole
     *
     * Delete Organization User Role.
     *
     */
    public function testDeleteOrganizationUserRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganization
     *
     * Get Organization.
     *
     */
    public function testGetOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationFeatureFlags
     *
     * List Organization Feature Flags.
     *
     */
    public function testGetOrganizationFeatureFlags()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationUserPermissions
     *
     * List Organization User Permissions.
     *
     */
    public function testGetOrganizationUserPermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationUserRoles
     *
     * List Organization User Roles.
     *
     */
    public function testGetOrganizationUserRoles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationUsers
     *
     * List Organization Users.
     *
     */
    public function testGetOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizations
     *
     * List Organizations.
     *
     */
    public function testGetOrganizations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeOrganizationUser
     *
     * Remove Organization User.
     *
     */
    public function testRemoveOrganizationUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganization
     *
     * Update Organization.
     *
     */
    public function testUpdateOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationFeatureFlagOverride
     *
     * Update Organization Feature Flag Override.
     *
     */
    public function testUpdateOrganizationFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationUsers
     *
     * Update Organization Users.
     *
     */
    public function testUpdateOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
