<?php
/**
 * OrganizationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kinde\KindeSDK\Test\Api;

use \Kinde\KindeSDK\Configuration;
use \Kinde\KindeSDK\ApiException;
use \Kinde\KindeSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinde\KindeSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addOrganizationUsers
     *
     * Assign Users to an Organization.
     *
     */
    public function testAddOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganization
     *
     * Create Organization.
     *
     */
    public function testCreateOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationFeatureFlagOverride
     *
     * Delete organization feature flag override.
     *
     */
    public function testDeleteOrganizationFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationFeatureFlagOverrides
     *
     * Delete all organization feature flag overrides.
     *
     */
    public function testDeleteOrganizationFeatureFlagOverrides()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrgainzations
     *
     * List Organizations.
     *
     */
    public function testGetOrgainzations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganization
     *
     * Get Organization.
     *
     */
    public function testGetOrganization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationUsers
     *
     * List Organization Users.
     *
     */
    public function testGetOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeOrganizationUsers
     *
     * Remove Users from an Organization.
     *
     */
    public function testRemoveOrganizationUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationFeatureFlagOverride
     *
     * Update organization feature flag override.
     *
     */
    public function testUpdateOrganizationFeatureFlagOverride()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
